name: Rensner Theme
version: 1.0
description: Custom theme built on top of the 'Dev' skeleton theme.
author: Adrian Schmieg
homepage: https://example.com
licence: ''

settings:
  myfield: My Default Value

forms:
  fields:

    listpages:
      type: text
      label: List Entries from Folder
      placeholder: /blog
      description: Add a path to a folder from which you want to list entries on startpage    

    myfield:
      type: text
      label: Label for my field
      placeholder: My placeholder
